In [81]:
from numpy import cov
import os
import pandas
import sys
from pytesmo.time_series.anomaly import calc_anomaly
from pytesmo.time_series.anomaly import calc_anomaly
sys.path.append('../python')
sys.path.append('../../icos_data')
sys.path.append('../../ismn_data\HOBE_Data_2015-2018')
import sm_config as config
import sm_tools as tools
import sm_triplecollocation

In [82]:
f = "matched_SMOS-IC_ERA5 0-1_ASCAT 12.5 TS_anomaly_879190.csv"
triplet = (f.split("_"))
triplet = (triplet[1], triplet[2], triplet[3])

In [83]:
dir = r"C:\Users\neene\Documents\LuDrive\academic\Lund\GISM01\Soil moisture thesis\test_results\20210314_sanity_check\tc_analysis_20210307181412\matched_data"

In [84]:
f = os.path.join(dir, f)

In [85]:
print(f)

C:\Users\neene\Documents\LuDrive\academic\Lund\GISM01\Soil moisture thesis\test_results\20210314_sanity_check\tc_analysis_20210307181412\matched_data\matched_SMOS-IC_ERA5 0-1_ASCAT 12.5 TS_anomaly_879190.csv


In [86]:
matched_data = tools.csv_to_pdseries(f)


In [87]:
print(matched_data)
print(matched_data.shape)

                      SMOS-IC  ERA5 0-1  ASCAT 12.5 TS
time                                                  
2015-04-01 05:00:00  0.031211 -0.011438      13.124371
2015-04-06 05:00:00 -0.070565 -0.011252      -1.277074
2015-04-11 05:00:00 -0.080283  0.016174       4.934201
2015-04-13 05:00:00 -0.022997  0.019963      -2.879258
2015-04-16 05:00:00 -0.059345 -0.000394      -2.602035
...                       ...       ...            ...
2018-12-17 05:00:00 -0.103184 -0.006385      -2.777856
2018-12-21 05:00:00  0.092757 -0.014696       2.066251
2018-12-22 05:00:00 -0.073962 -0.015705       3.006251
2018-12-25 05:00:00  0.017992 -0.021385       4.324998
2018-12-30 05:00:00 -0.048241 -0.000053      -6.696249

[317 rows x 3 columns]
(317, 3)


In [93]:
x = matched_data[triplet[0]].to_numpy()
y = matched_data[triplet[1]].to_numpy()
z = matched_data[triplet[2]].to_numpy()

In [98]:
# matches grey nearing matlab
print(cov(x,x))
print(cov(x,y))
print(cov(x,z))
print(cov(y,y))
print(cov(y,z))
print(cov(z,z))

[[0.00954269 0.00954269]
 [0.00954269 0.00954269]]
[[0.00954269 0.00034926]
 [0.00034926 0.00054809]]
[[9.54269054e-03 3.23244544e-01]
 [3.23244544e-01 1.73916414e+02]]
[[0.00054809 0.00054809]
 [0.00054809 0.00054809]]
[[5.48086285e-04 8.31819597e-02]
 [8.31819597e-02 1.73916414e+02]]
[[173.91641414 173.91641414]
 [173.91641414 173.91641414]]


In [92]:
tcol_cov = tools.calc_tcol_cov(matched_data[triplet[0]].to_numpy(),
                               matched_data[triplet[1]].to_numpy(),
                               matched_data[triplet[2]].to_numpy())
print(tcol_cov)

[[9.54269054e-03 3.49257629e-04 3.23244544e-01]
 [5.48086285e-04 8.31819597e-02 3.49257629e-04]
 [1.73916414e+02 3.23244544e-01 8.31819597e-02]]


In [99]:
snr, err_std, beta = tools.calc_tcol_snr(matched_data[triplet[0]].to_numpy(),
                                         matched_data[triplet[1]].to_numpy(),
                                         matched_data[triplet[2]].to_numpy())

r = tools.calc_tcol_r(snr)

print(snr)
print(err_std)
print(beta)
print(r)

[-7.80396073 -7.07420965 -1.00043479]
[-7.80396073 -7.07420965 -1.00043479]
[0.09047363 0.08318298 0.04133764]
[1.         3.88599337 0.00419872]
[ 1.07096835  1.07918046 47.96851992]
