In [2]:
import os
from datetime import datetime
from gldas.interface import GLDAS_Noah_v21_025Ds

In [3]:
os.getcwd()

'C:\\git\\soil-moisture-sweden\\python'

In [4]:
data_path = r'C:\git\soil-moisture-sweden\sm_sample_files\gldas-noah-2.1-0.25deg'

# test that we are in the right dir
# os.listdir(data_path)[0]

In [5]:
# reader for multiple images

# read several parameters
# parameter = ['lat', 'lon', 'SoilMoi0_10cm_inst']
# the class is initialized with the exact filename.
gldas_reader = GLDAS_Noah_v21_025Ds(data_path)
gldas_reader.read_bulk = True

# NOTE: have to suppress subpath_templ to read files that are all in one directory
gldas_reader.subpath_templ = []

In [6]:
for whatever in gldas_reader.daily_images(datetime(2018,6,3)):
    print(whatever)

In [7]:
gldas_image = gldas_reader.read(datetime(2018,6,3,0,0))
help(gldas_image)
print(gldas_image.lon.shape)
print(gldas_image.data['SoilMoi0_10cm_inst'].shape)

Help on Image in module pygeobase.object_base object:

class Image(builtins.object)
 |  The Image class represents the base object of an image.
 |  
 |  Parameters
 |  ----------
 |  lon : numpy.array
 |      array of longitudes
 |  lat : numpy.array
 |      array of latitudes
 |  data : dict
 |      dictionary of numpy arrays that holds the image data for each
 |      variable of the dataset
 |  metadata : dict
 |      dictionary that holds metadata
 |  timestamp : datetime.datetime
 |      exact timestamp of the image
 |  timekey : str, optional
 |      Key of the time variable, if available, stored in data dictionary.
 |  
 |  Methods defined here:
 |  
 |  __getitem__(self, key)
 |  
 |  __init__(self, lon, lat, data, metadata, timestamp, timekey=None)
 |      Initialization of the image object.
 |  
 |  __iter__(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance 

In [8]:
help

Type help() for interactive help, or help(object) for help about object.

In [9]:
for gldas_data, metadata, timestamp, lons, lats, time_var in gldas_reader.daily_images(datetime(2018,6,1)):

    # this tells you the exact timestamp of the read image
    print(timestamp.isoformat())
    print(type(gldas_data))
    
    # the data is a dictionary, each dictionary key contains the array of one variable
    print("The following variables are in this image", gldas_data.keys())
    # print(gldas_data.shape)
    # print(h08_data['ssm'].shape)
    # print(lons.shape)
    # print(lats.shape)
    # print(gldas_data['SoilMoi0_10cm_inst'].shape)
    print(lons)

2018-06-01T00:00:00
<class 'dict'>
The following variables are in this image dict_keys(['SoilMoi0_10cm_inst'])
[[-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 ...
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]]
2018-06-01T03:00:00
<class 'dict'>
The following variables are in this image dict_keys(['SoilMoi0_10cm_inst'])
[[-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 ...
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]
 [-179.875 -179.625 -179.375 ...  179.375  179.625  179.875]]
2018-06-01T06:00:00
<class 'dict'>

In [10]:
help(gldas_reader)

Help on GLDAS_Noah_v21_025Ds in module gldas.interface object:

class GLDAS_Noah_v21_025Ds(pygeobase.io_base.MultiTemporalImageBase)
 |  Class for reading GLDAS v2.1 images in nc format.
 |  
 |  Parameters
 |  ----------
 |  data_path : string
 |      Path to the nc files
 |  parameter : string or list, optional
 |      one or list of parameters to read, see GLDAS v2.1 documentation 
 |      for more information (default: 'SoilMoi0_10cm_inst').
 |  subgrid : Cell Grid
 |      Subgrid of the global GLDAS Grid to use for reading image data (e.g only land points)
 |  array_1D: boolean, optional
 |      If set then the data is read into 1D arrays.
 |      Needed for some legacy code.
 |  
 |  Method resolution order:
 |      GLDAS_Noah_v21_025Ds
 |      pygeobase.io_base.MultiTemporalImageBase
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, data_path, parameter='SoilMoi0_10cm_inst', subgrid=None, array_1D=False)
 |      Initialize self.  See help(type(self))

In [11]:
gldas_reader.tstamps_for_daterange(datetime(2018,6,1), datetime(2018,6,30))

[datetime.datetime(2018, 6, 1, 0, 0),
 datetime.datetime(2018, 6, 1, 3, 0),
 datetime.datetime(2018, 6, 1, 6, 0),
 datetime.datetime(2018, 6, 1, 9, 0),
 datetime.datetime(2018, 6, 1, 12, 0),
 datetime.datetime(2018, 6, 1, 15, 0),
 datetime.datetime(2018, 6, 1, 18, 0),
 datetime.datetime(2018, 6, 1, 21, 0),
 datetime.datetime(2018, 6, 2, 0, 0),
 datetime.datetime(2018, 6, 2, 3, 0),
 datetime.datetime(2018, 6, 2, 6, 0),
 datetime.datetime(2018, 6, 2, 9, 0),
 datetime.datetime(2018, 6, 2, 12, 0),
 datetime.datetime(2018, 6, 2, 15, 0),
 datetime.datetime(2018, 6, 2, 18, 0),
 datetime.datetime(2018, 6, 2, 21, 0),
 datetime.datetime(2018, 6, 3, 0, 0),
 datetime.datetime(2018, 6, 3, 3, 0),
 datetime.datetime(2018, 6, 3, 6, 0),
 datetime.datetime(2018, 6, 3, 9, 0),
 datetime.datetime(2018, 6, 3, 12, 0),
 datetime.datetime(2018, 6, 3, 15, 0),
 datetime.datetime(2018, 6, 3, 18, 0),
 datetime.datetime(2018, 6, 3, 21, 0),
 datetime.datetime(2018, 6, 4, 0, 0),
 datetime.datetime(2018, 6, 4, 3, 0),


In [15]:
test_image = gldas_reader.read(datetime(2018, 6, 3, 3, 0))

In [16]:
help(test_image)

Help on Image in module pygeobase.object_base object:

class Image(builtins.object)
 |  The Image class represents the base object of an image.
 |  
 |  Parameters
 |  ----------
 |  lon : numpy.array
 |      array of longitudes
 |  lat : numpy.array
 |      array of latitudes
 |  data : dict
 |      dictionary of numpy arrays that holds the image data for each
 |      variable of the dataset
 |  metadata : dict
 |      dictionary that holds metadata
 |  timestamp : datetime.datetime
 |      exact timestamp of the image
 |  timekey : str, optional
 |      Key of the time variable, if available, stored in data dictionary.
 |  
 |  Methods defined here:
 |  
 |  __getitem__(self, key)
 |  
 |  __init__(self, lon, lat, data, metadata, timestamp, timekey=None)
 |      Initialization of the image object.
 |  
 |  __iter__(self)
 |  
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |  
 |  __dict__
 |      dictionary for instance 

In [12]:
# gldas_time_series = gldas_reader.read(19.556539, 64.182029)
# gldas_time_series = gldas_reader._read_lonlat(19.556539, 64.182029)
